theme: jekyll-theme-minimal
title: Tharen Candi
description:  ~ Computer science Bachelor @ USYD and EPFL ~                          My interest in computing started at the age of 13 by building computers, creating servers, writing terminal programs in c# and video games within the Unity engine, as well as analog and digital circuits through general electronics and the Arduino microcontroller. I have skills in graphic design/ digital illustration and hold a deep love for piano, guitar, music theory, music production, and sound engineering.
show_downloads: true
